# Generated by Django 4.1.7 on 2023-03-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(
                error_messages={"unique": "Username already exists"},
                max_length=127,
                unique=True,
            ),
        ),
    ]
