# Generated by Django 4.1.7 on 2023-03-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Username already exists"},
                max_length=127,
                unique=True,
            ),
        ),
    ]
