# Generated by Django 4.1.7 on 2023-03-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_employee",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Administrador", "Administrador"),
                    ("Vendedor", "Vendedor"),
                    ("Cliente", "Cliente"),
                ],
                default="Cliente",
                max_length=50,
            ),
        ),
    ]
