# Generated by Django 4.1.7 on 2023-03-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_user"),
        ("shopping_carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="orders",
            field=models.ManyToManyField(
                related_name="ordered_products",
                through="shopping_carts.OrderedCarts",
                to="products.product",
            ),
        ),
    ]
