# Generated by Django 4.1.7 on 2023-03-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_carts", "0002_shoppingcart_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
