# Generated by Django 4.1.7 on 2023-03-10 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_carts", "0004_productcarts_remove_shoppingcart_is_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcarts",
            name="quant",
        ),
    ]
