# Generated by Django 4.1.7 on 2023-03-13 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_remove_orderedproducts_quant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.CreateModel(
            name="PurchaseSaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_sale_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="purchase_sale_order",
            field=models.ManyToManyField(
                related_name="orders",
                through="orders.PurchaseSaleOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
