# Generated by Django 4.1.7 on 2023-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_user_purchasesaleorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasesaleorder",
            name="is_sale_order",
            field=models.BooleanField(default=False),
        ),
    ]
