# Generated by Django 4.1.7 on 2023-03-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("stock", models.IntegerField(default=0)),
                ("is_avaiable", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("description", models.CharField(max_length=255, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="products",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
