# Generated by Django 4.1.7 on 2023-03-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
